[package]
name = "devmap-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
devmap-extract = { path = "../devmap-extract" }
devmap-resolve = { path = "../devmap-resolve" }
devmap-analyze = { path = "../devmap-analyze" }
rusqlite.workspace = true
serde_json.workspace = true
anyhow.workspace = true
rayon.workspace = true

[dev-dependencies]
devmap-serve = { path = "../devmap-serve" }
