"""`dev wiki` — generate and maintain the agent-facing codebase wiki.

An OpenWiki-style, self-maintaining wiki of this repository, emitted as an OKF bundle
under ``.devcouncil/knowledge/okf/wiki/`` so pages are automatically injected into
planning/council/task prompts as knowledge sources (and are exportable/renderable with
the existing ``dev okf`` tooling).

* ``dev wiki update`` (alias ``generate``) — build the wiki, or refresh only the pages
  whose repo-map slice changed. With a configured model, new/stale pages are enriched
  with LLM-written prose by the ``wiki_writer`` role; without one, the deterministic
  skeleton is used.
* ``dev wiki status`` — show which pages are fresh vs stale against the current map.
* ``dev wiki install-action`` — write a GitHub Action that keeps the wiki updated by
  opening a PR when the map drifts (the OpenWiki maintenance pattern).
"""

from __future__ import annotations

import logging
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from devcouncil.cli.commands.init import initialize_project
from devcouncil.indexing.repo_mapper import RepoMap

app = typer.Typer(help="Generate and maintain the agent-facing codebase wiki (OKF bundle).")
console = Console()
logger = logging.getLogger(__name__)

_WORKFLOW_PATH = Path(".github") / "workflows" / "devcouncil-wiki-update.yml"

_WIKI_WORKFLOW = """\
# DevCouncil codebase wiki — automatic maintenance.
#
# Generated by `dev wiki install-action`. Nightly (and on demand) this rebuilds the
# repository map, refreshes the stale wiki pages, and opens a PR when anything changed —
# so the agent-facing documentation tracks the code without anyone remembering to run it.
#
# The refresh runs with --no-llm by default (deterministic, no secrets needed). To get
# LLM-enriched prose in CI, add your provider API key as a repository secret and export
# it in the "Update wiki" step (e.g. OPENROUTER_API_KEY).
name: DevCouncil Wiki Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # nightly (UTC); adjust or remove as needed

permissions:
  contents: write
  pull-requests: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - name: Install DevCouncil
        run: |
          uv tool install devcouncil
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Update wiki
        run: |
          dev map --no-wiki > /dev/null
          dev wiki update --no-llm
      - name: Open PR if the wiki changed
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs: refresh DevCouncil codebase wiki"
          title: "Refresh DevCouncil codebase wiki"
          body: >
            Automated wiki refresh: the repository map drifted from the last generated
            wiki. Review the page diffs and merge to keep agent-facing docs current.
          branch: devcouncil/wiki-update
          add-paths: |
            .devcouncil/knowledge/okf/wiki/**
"""

# .gitignore rules that make the wiki committable in repos that ignore .devcouncil/*
# (the default DevCouncil layout). Appended by `dev wiki install-action` when needed.
_GITIGNORE_UNIGNORE = """\

# DevCouncil codebase wiki: shared knowledge-as-code, maintained by `dev wiki update`.
!.devcouncil/knowledge/
.devcouncil/knowledge/*
!.devcouncil/knowledge/okf/
.devcouncil/knowledge/okf/*
!.devcouncil/knowledge/okf/wiki/
"""


def wiki_dir_for(root: Path) -> Path:
    from devcouncil.knowledge.wiki import wiki_dir_for as _wiki_dir_for

    return _wiki_dir_for(root)


def _load_repo_map(root: Path, *, remap: bool) -> RepoMap:
    """Load .devcouncil/repo_map.json, (re)generating it when missing or on --remap."""
    map_path = root / ".devcouncil" / "repo_map.json"
    if remap or not map_path.is_file():
        from devcouncil.cli.commands.map import generate_map_artifacts

        console.print("[dim]Building repository map...[/dim]")
        return generate_map_artifacts(root, map_path)
    return RepoMap.model_validate_json(map_path.read_text(encoding="utf-8"))


def _print_result(result) -> None:
    if result.changed:
        console.print(
            f"[green]Wiki updated:[/green] {len(result.created)} created, "
            f"{len(result.updated)} updated, {len(result.skipped)} unchanged "
            f"([cyan]{result.wiki_dir}[/cyan])."
        )
    else:
        console.print(
            f"[green]Wiki is up to date[/green] ({len(result.skipped)} pages, "
            f"[cyan]{result.wiki_dir}[/cyan])."
        )
    if result.enriched:
        console.print(f"[green]LLM-enriched {len(result.enriched)} page(s).[/green]")
    if result.problems:
        console.print(f"[yellow]{len(result.problems)} OKF validation issue(s):[/yellow]")
        for p in result.problems[:10]:
            console.print(f"  - {p}")


def _update(
    project_root: Path,
    *,
    llm: bool,
    force: bool,
    remap: bool,
) -> None:
    root = project_root.expanduser().resolve()
    from devcouncil.telemetry.logging_setup import set_log_dir

    set_log_dir(root)
    logger.info("dev wiki update: llm=%s force=%s remap=%s", llm, force, remap)
    initialize_project(root, quiet=True)

    from devcouncil.knowledge.wiki import refresh_wiki

    result = refresh_wiki(root, llm=llm, force=force, remap=remap)
    _print_result(result)


@app.command("update")
def update(
    project_root: Path = typer.Option(Path("."), "--project-root", help="Repository root containing .devcouncil/."),
    llm: bool = typer.Option(True, "--llm/--no-llm", help="Enrich new/stale pages with LLM-written prose (degrades to the skeleton without a configured model)."),
    force: bool = typer.Option(False, "--force", help="Rewrite (and re-enrich) every page, ignoring fingerprints."),
    remap: bool = typer.Option(False, "--remap", help="Rebuild .devcouncil/repo_map.json first."),
) -> None:
    """Create the wiki, or refresh only the pages whose repo-map slice changed."""
    _update(project_root, llm=llm, force=force, remap=remap)


@app.command("generate")
def generate(
    project_root: Path = typer.Option(Path("."), "--project-root", help="Repository root containing .devcouncil/."),
    llm: bool = typer.Option(True, "--llm/--no-llm", help="Enrich pages with LLM-written prose."),
    force: bool = typer.Option(False, "--force", help="Rewrite (and re-enrich) every page."),
    remap: bool = typer.Option(False, "--remap", help="Rebuild .devcouncil/repo_map.json first."),
) -> None:
    """Alias of `dev wiki update`."""
    _update(project_root, llm=llm, force=force, remap=remap)


@app.command("read")
def read(
    page: str | None = typer.Option(None, "--page", help="Fetch one wiki page by relative path."),
    query: str | None = typer.Option(None, "--query", help="Search wiki pages by keyword."),
    project_root: Path = typer.Option(Path("."), "--project-root", help="Repository root containing .devcouncil/."),
    json_output: bool = typer.Option(False, "--json", help="Emit machine-readable JSON."),
) -> None:
    """Read the generated codebase wiki (list, fetch, or search)."""
    from devcouncil.knowledge.wiki_read import read_wiki_page

    root = project_root.expanduser().resolve()
    payload = read_wiki_page(root, page=page, query=query)
    if json_output:
        console.print_json(data=payload)
        if not payload.get("ok", True):
            raise typer.Exit(code=1)
        return
    if not payload.get("ok", True):
        console.print(f"[red]{payload.get('error')}[/red]")
        raise typer.Exit(code=1)
    if "pages" in payload:
        pages = payload["pages"]
        if isinstance(pages, list):
            for item in pages:
                if isinstance(item, dict):
                    console.print(f"- {item.get('page')}: {item.get('title')}")
        return
    console.print(payload.get("body") or "")


@app.command("status")
def status(
    project_root: Path = typer.Option(Path("."), "--project-root", help="Repository root containing .devcouncil/."),
    json_output: bool = typer.Option(False, "--json", help="Emit machine-readable JSON."),
) -> None:
    """Show which wiki pages are fresh vs stale against the current repository map."""
    root = project_root.expanduser().resolve()
    from devcouncil.telemetry.logging_setup import set_log_dir

    set_log_dir(root)

    wiki_dir = wiki_dir_for(root)
    if not (wiki_dir / "index.md").is_file():
        if json_output:
            console.print_json(data={"exists": False, "wiki_dir": str(wiki_dir)})
        else:
            console.print(
                f"[yellow]No wiki found at[/yellow] {wiki_dir}. Run [bold]dev wiki update[/bold] to create it."
            )
        raise typer.Exit(code=1)

    repo_map = _load_repo_map(root, remap=False)
    from devcouncil.knowledge.wiki import _page_fingerprints, wiki_stale_pages

    stale = wiki_stale_pages(root, repo_map, wiki_dir)
    total = len(_page_fingerprints(repo_map))

    if json_output:
        console.print_json(data={
            "exists": True,
            "wiki_dir": str(wiki_dir),
            "pages": total,
            "stale": stale,
            "fresh": total - len(stale),
        })
        return

    if not stale:
        console.print(f"[green]✓ Wiki is fresh[/green] — {total} page(s) match the current repo map.")
        return

    table = Table(title=f"Stale wiki pages ({len(stale)}/{total})")
    table.add_column("Page", overflow="fold")
    table.add_column("Reason")
    for rel_path, reason in sorted(stale.items()):
        table.add_row(rel_path, reason)
    console.print(table)
    console.print("Run [bold]dev wiki update[/bold] to refresh them.")


@app.command("install-action")
def install_action(
    project_root: Path = typer.Option(Path("."), "--project-root", help="Repository root containing .devcouncil/."),
    force: bool = typer.Option(False, "--force", help="Overwrite an existing workflow file."),
) -> None:
    """Install a GitHub Action that keeps the wiki updated via automated PRs."""
    root = project_root.expanduser().resolve()
    target = root / _WORKFLOW_PATH
    if target.exists() and not force:
        console.print(f"[yellow]{target} already exists; use --force to overwrite.[/yellow]")
        raise typer.Exit(code=1)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_WIKI_WORKFLOW, encoding="utf-8")
    console.print(f"[green]Wrote[/green] {target}. The wiki will refresh nightly via PR.")

    # The default DevCouncil .gitignore ignores .devcouncil/* — un-ignore the wiki so
    # the workflow's PRs can actually commit it.
    gitignore = root / ".gitignore"
    if gitignore.is_file():
        content = gitignore.read_text(encoding="utf-8")
        if ".devcouncil" in content and "!.devcouncil/knowledge/okf/wiki/" not in content:
            gitignore.write_text(content.rstrip("\n") + "\n" + _GITIGNORE_UNIGNORE, encoding="utf-8")
            console.print("[green]Updated .gitignore[/green] so the wiki is committable.")
