"""Scaffold a starter GitHub Actions workflow for a target repository.

DevCouncil already knows a project's test/lint/typecheck commands (config.yaml), so
it can emit a sensible CI starter that runs them. The workflow is a *template* the
user can adjust; scaffolding never overwrites an existing workflow unless forced.
"""

from __future__ import annotations

from pathlib import Path

from devcouncil.app.config import DevCouncilConfig, load_config

WORKFLOW_RELPATH = Path(".github") / "workflows" / "devcouncil.yml"

_PYTHON_TOOLS = {
    "pytest", "flake8", "ruff", "mypy", "tox", "python", "python3", "uv",
    "poetry", "black", "isort", "pyright",
}
_NODE_TOOLS = {
    "npm", "npx", "pnpm", "yarn", "bun", "eslint", "tsc", "jest", "vitest", "node",
}
_PYTHON_MARKERS = ("pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", "Pipfile")


def detect_stacks(project_root: Path) -> set[str]:
    """Best-effort detection of the language stacks present in the repo."""
    stacks: set[str] = set()
    if any((project_root / marker).exists() for marker in _PYTHON_MARKERS):
        stacks.add("python")
    if (project_root / "package.json").exists():
        stacks.add("node")
    return stacks


def _command_stack(command: str) -> str | None:
    tool = command.split()[0] if command.strip() else ""
    if tool in _PYTHON_TOOLS:
        return "python"
    if tool in _NODE_TOOLS:
        return "node"
    return None


def _applicable_commands(commands: list[str], stacks: set[str]) -> list[str]:
    """Keep commands whose tool matches a detected stack; if none detected, keep all."""
    if not stacks:
        return list(commands)
    kept = []
    for command in commands:
        stack = _command_stack(command)
        if stack is None or stack in stacks:
            kept.append(command)
    return kept


# Optional dependency-audit step per stack. Emitted only when the matching stack is
# detected, so a Python-only repo never gets an npm audit (and vice versa). These are
# non-blocking (continue-on-error) starters the user can tighten.
_AUDIT_STEPS: dict[str, list[str]] = {
    "python": [
        "      - name: Dependency audit (pip-audit)",
        "        continue-on-error: true",
        "        run: pip-audit",
    ],
    "node": [
        "      - name: Dependency audit (npm audit)",
        "        continue-on-error: true",
        "        run: npm audit --audit-level=high",
    ],
}


def _add_audit_steps(steps: list[str], stacks: set[str]) -> None:
    """Append an optional SCA audit step for each detected stack (only)."""
    for stack in sorted(stacks):
        steps.extend(_AUDIT_STEPS.get(stack, []))


def _python_version(project_root: Path) -> str:
    version_file = project_root / ".python-version"
    if version_file.exists():
        first = version_file.read_text(encoding="utf-8").strip().splitlines()
        if first and first[0].strip():
            return first[0].strip()
    return "3.12"


def render_workflow(
    project_root: Path,
    default_branch: str = "main",
    config: DevCouncilConfig | None = None,
) -> str:
    """Render the workflow YAML text deterministically from config + detected stacks."""
    if config is None:
        config = load_config(project_root)
    stacks = detect_stacks(project_root)
    commands = config.commands

    steps: list[str] = [
        "      - name: Checkout",
        "        uses: actions/checkout@v4",
    ]
    if "python" in stacks:
        steps += [
            "      - name: Set up Python",
            "        uses: actions/setup-python@v5",
            "        with:",
            f'          python-version: "{_python_version(project_root)}"',
        ]
    if "node" in stacks:
        steps += [
            "      - name: Set up Node",
            "        uses: actions/setup-node@v4",
            "        with:",
            '          node-version: "20"',
        ]

    def add_command_steps(label: str, raw_commands: list[str]) -> None:
        for command in _applicable_commands(raw_commands, stacks):
            steps.append(f"      - name: {label} ({command.split()[0]})")
            steps.append(f"        run: {command}")

    add_command_steps("Lint", commands.lint)
    add_command_steps("Typecheck", commands.typecheck)
    add_command_steps("Test", commands.test)
    _add_audit_steps(steps, stacks)

    body = "\n".join(steps)
    return (
        "# Starter CI workflow generated by DevCouncil from .devcouncil/config.yaml.\n"
        "# Adjust the setup steps, dependency install, and commands for your stack.\n"
        "name: DevCouncil CI\n"
        "\n"
        "on:\n"
        "  push:\n"
        f'    branches: ["{default_branch}"]\n'
        "  pull_request:\n"
        f'    branches: ["{default_branch}"]\n'
        "\n"
        "jobs:\n"
        "  checks:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        f"{body}\n"
    )


def scaffold_ci(project_root: Path, force: bool = False) -> Path | None:
    """Write the starter workflow. Returns the path, or None if one already exists.

    Does not overwrite an existing ``.github/workflows/devcouncil.yml`` unless
    ``force`` is set, so re-running is safe and user edits are preserved.
    """
    project_root = project_root.resolve()
    target = project_root / WORKFLOW_RELPATH
    if target.exists() and not force:
        return None
    config = load_config(project_root)
    default_branch = config.project.default_branch or "main"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        render_workflow(project_root, default_branch, config), encoding="utf-8"
    )
    return target
