"""Confidence hardening for unwired / dead-code / unreachable classification.

Characterizes real-world false-positive shapes observed on large Go+Python
repos (generated gRPC stubs, ``//go:embed`` carriers, ``func init()`` loaders,
externally-launched entry scripts, launcher-file references, re-export-only
package inits, dynamic ``globals()`` dispatch) and locks in the fail-closed
contract: uncertainty lowers confidence, never raises it, while genuinely dead
code stays at extracted tier.
"""

from __future__ import annotations

import subprocess



def _git(root, *args):
    subprocess.run(["git", *args], cwd=root, check=True, capture_output=True, text=True)


def _commit(root):
    _git(root, "init")
    _git(root, "-c", "user.email=t@t", "-c", "user.name=t", "add", "-A")
    _git(root, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-m", "init")


def _write(tmp_path, files):
    for rel, content in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")


_PYPROJECT = (
    '[project]\nname="t"\nversion="0"\n[project.scripts]\ncli="pkg.main:main"\n'
)

_PB2_HEADER = (
    "# -*- coding: utf-8 -*-\n"
    "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
    "# source: llm.proto\n"
)
_PB2_GRPC_HEADER = (
    "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n"
)


# ---------------------------------------------------------------------------
# 1. Generated files must never be extracted-tier dead / unwired
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# 2. Go side-effect carriers: //go:embed and func init()
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# 3. Python entry-point shapes
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# 4. Re-export-only __init__.py package markers
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# 5. Dynamic-usage evidence must keep symbols off the extracted tier
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# 6. Fail closed when the check cannot run (language support)
# ---------------------------------------------------------------------------


def test_go_liveness_disabled_without_tree_sitter(monkeypatch):
    """Without tree-sitter, Go call edges cannot be extracted — Go files must
    drop out of file liveness instead of flooding unwired (fail closed)."""
    from devcouncil.indexing import ts_imports
    from devcouncil.indexing.wiring import is_liveness_code_file

    monkeypatch.setattr(ts_imports, "tree_sitter_available", lambda: False)
    assert is_liveness_code_file("pkg/main.py") is True
    assert is_liveness_code_file("internal/thing.go") is False


# ---------------------------------------------------------------------------
# 7. True positives must survive the hardening
# ---------------------------------------------------------------------------


