"""Confidence hardening for unwired / dead-code / unreachable classification.

Characterizes real-world false-positive shapes observed on large Go+Python
repos (generated gRPC stubs, ``//go:embed`` carriers, ``func init()`` loaders,
externally-launched entry scripts, launcher-file references, re-export-only
package inits, dynamic ``globals()`` dispatch) and locks in the fail-closed
contract: uncertainty lowers confidence, never raises it, while genuinely dead
code stays at extracted tier.
"""

from __future__ import annotations

import subprocess

from devcouncil.indexing.graph.build import build_code_graph
from devcouncil.indexing.graph.schema import Confidence


def _git(root, *args):
    subprocess.run(["git", *args], cwd=root, check=True, capture_output=True, text=True)


def _commit(root):
    _git(root, "init")
    _git(root, "-c", "user.email=t@t", "-c", "user.name=t", "add", "-A")
    _git(root, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-m", "init")


def _write(tmp_path, files):
    for rel, content in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")


_PYPROJECT = (
    '[project]\nname="t"\nversion="0"\n[project.scripts]\ncli="pkg.main:main"\n'
)

_PB2_HEADER = (
    "# -*- coding: utf-8 -*-\n"
    "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
    "# source: llm.proto\n"
)
_PB2_GRPC_HEADER = (
    "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n"
)


# ---------------------------------------------------------------------------
# 1. Generated files must never be extracted-tier dead / unwired
# ---------------------------------------------------------------------------


def test_pb2_generated_files_never_unwired_or_dead(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "proto/llm_pb2.py": _PB2_HEADER + "DESCRIPTOR = None\n",
        "proto/llm_pb2_grpc.py": (
            _PB2_GRPC_HEADER
            + "class LlmStub:\n"
            + "    def Generate(self, request):\n"
            + "        return request\n"
        ),
        "proto/wisdev.pb.go": (
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n"
            "package proto\n\n"
            "type Wisdev struct{}\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    for gen in ("proto/llm_pb2.py", "proto/llm_pb2_grpc.py", "proto/wisdev.pb.go"):
        assert gen not in graph.unwired_candidates, graph.unwired_candidates
        assert gen not in graph.unreachable_files, graph.unreachable_files
    assert not any(
        d.path.startswith("proto/") for d in graph.dead_code
    ), [(d.id, d.confidence) for d in graph.dead_code if d.path.startswith("proto/")]


def test_generated_header_without_pattern_name_not_unwired(tmp_path):
    """Header sniff must catch generated files whose names carry no pattern."""
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "gen/schema_types.py": (
            "# Code generated by schemagen. DO NOT EDIT.\n"
            "SCHEMA = {}\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "gen/schema_types.py" not in graph.unwired_candidates, graph.unwired_candidates


def test_generated_marker_deep_in_file_does_not_exempt(tmp_path):
    """Only file-head comment markers count — a body mention is not a header."""
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "pkg/orphan.py": (
            "X = 1\n"
            "Y = 2\n"
            "Z = 3\n"
            "A = 4\n"
            "B = 5\n"
            "NOTE = 1  # reminds reviewers: code generated by hand, DO NOT EDIT casually\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "pkg/orphan.py" in graph.unwired_candidates, graph.unwired_candidates


# ---------------------------------------------------------------------------
# 2. Go side-effect carriers: //go:embed and func init()
# ---------------------------------------------------------------------------


def test_go_embed_asset_carrier_not_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "go.mod": "module example.com/app\n\ngo 1.21\n",
        "internal/mcp_assets/embed.go": (
            "package mcp_assets\n\n"
            'import "embed"\n\n'
            "//go:embed all:dist\n"
            "var Dist embed.FS\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "internal/mcp_assets/embed.go" not in graph.unwired_candidates, (
        graph.unwired_candidates
    )


def test_go_init_side_effect_loader_not_unwired_and_init_not_dead(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "go.mod": "module example.com/app\n\ngo 1.21\n",
        "internal/envload/dotenv.go": (
            "package envload\n\n"
            'import "os"\n\n'
            "func init() {\n"
            '\tos.Setenv("LOADED", "1")\n'
            "}\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "internal/envload/dotenv.go" not in graph.unwired_candidates, (
        graph.unwired_candidates
    )
    # Runtime-invoked Go init/main must never appear in dead code at any tier.
    assert not any(
        d.path.endswith(".go") and d.id.rsplit("::", 1)[-1].split(".")[-1] in {"init", "main"}
        for d in graph.dead_code
    ), graph.dead_code


# ---------------------------------------------------------------------------
# 3. Python entry-point shapes
# ---------------------------------------------------------------------------


def test_python_main_guard_app_not_unwired_or_unreachable(tmp_path):
    """Apps launched by external process managers carry a __main__ guard."""
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "sidecar/manuscript_app.py": (
            "def serve():\n"
            "    return 1\n"
            "\n"
            'if __name__ == "__main__":\n'
            "    serve()\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "sidecar/manuscript_app.py" not in graph.unwired_candidates, (
        graph.unwired_candidates
    )
    assert "sidecar/manuscript_app.py" not in graph.unreachable_files, (
        graph.unreachable_files
    )


def test_dockerfile_cmd_reference_clears_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "services/side/Dockerfile": (
            "FROM python:3.12-slim\n"
            "COPY . /app\n"
            "WORKDIR /app\n"
            'CMD ["python", "runner.py"]\n'
        ),
        "services/side/runner.py": "def run():\n    return 1\nrun()\n",
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "services/side/runner.py" not in graph.unwired_candidates, (
        graph.unwired_candidates
    )


def test_procfile_dash_m_reference_clears_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "pkg/qrunner.py": "def loop():\n    return 1\n",
        "Procfile": "worker: python -m pkg.qrunner\n",
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "pkg/qrunner.py" not in graph.unwired_candidates, graph.unwired_candidates


def test_compose_command_reference_clears_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "pkg/jobs.py": "def tick():\n    return 1\n",
        "docker-compose.yml": (
            "services:\n"
            "  worker:\n"
            "    image: python:3.12\n"
            "    command: python -m pkg.jobs\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "pkg/jobs.py" not in graph.unwired_candidates, graph.unwired_candidates


def test_package_json_scripts_reference_clears_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "package.json": (
            '{"name": "x", "scripts": {"worker": "node tools-runtime/qworker.js"}}\n'
        ),
        "tools-runtime/qworker.js": "function work() { return 1 }\nwork();\n",
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "tools-runtime/qworker.js" not in graph.unwired_candidates, (
        graph.unwired_candidates
    )


def test_uvicorn_module_attr_reference_clears_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "sidecar/api_app.py": "app = object()\n",
        "sidecar/Dockerfile": (
            "FROM python:3.12-slim\n"
            'CMD ["uvicorn", "api_app:app", "--host", "0.0.0.0"]\n'
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "sidecar/api_app.py" not in graph.unwired_candidates, graph.unwired_candidates


# ---------------------------------------------------------------------------
# 4. Re-export-only __init__.py package markers
# ---------------------------------------------------------------------------


def test_reexport_only_init_not_unwired(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "apiapp/__init__.py": "",
        "apiapp/routers/__init__.py": (
            "from .health import router\n"
            '__all__ = ["router"]\n'
        ),
        "apiapp/routers/health.py": "def router():\n    return 1\n",
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "apiapp/routers/__init__.py" not in graph.unwired_candidates, (
        graph.unwired_candidates
    )
    assert "apiapp/__init__.py" not in graph.unwired_candidates, graph.unwired_candidates


def test_init_with_real_definitions_still_unwired(tmp_path):
    """An unimported __init__.py that defines behavior is real signal — keep it."""
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "island/__init__.py": (
            "def compute_thing():\n"
            "    return 42\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "island/__init__.py" in graph.unwired_candidates, graph.unwired_candidates


# ---------------------------------------------------------------------------
# 5. Dynamic-usage evidence must keep symbols off the extracted tier
# ---------------------------------------------------------------------------


def test_globals_dispatch_string_not_extracted_dead(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/tasks.py": (
            "def task_entry():\n"
            "    return 1\n"
            "def run():\n"
            "    return globals()['task_entry']()\n"
        ),
        "pkg/main.py": (
            "from pkg.tasks import run\n"
            "def main():\n"
            "    return run()\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert not any(
        d.id.endswith("::task_entry") and d.confidence == Confidence.EXTRACTED
        for d in graph.dead_code
    ), graph.dead_code


def test_hasattr_probe_string_not_extracted_dead(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/plugins.py": (
            "class Plugin:\n"
            "    pass\n"
            "def optional_hook():\n"
            "    return 1\n"
        ),
        "pkg/main.py": (
            "import pkg.plugins as plugins\n"
            "def main():\n"
            "    if hasattr(plugins, 'optional_hook'):\n"
            "        return 1\n"
            "    return 0\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert not any(
        d.id.endswith("::optional_hook") and d.confidence == Confidence.EXTRACTED
        for d in graph.dead_code
    ), graph.dead_code


# ---------------------------------------------------------------------------
# 6. Fail closed when the check cannot run (language support)
# ---------------------------------------------------------------------------


def test_go_symbols_never_extracted_tier(tmp_path):
    """Token scan covers py/js only — Go symbols must cap below extracted."""
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "go.mod": "module example.com/app\n\ngo 1.21\n",
        "main.go": (
            "package main\n\n"
            "func Spare() int { return 1 }\n\n"
            "func main() {\n"
            "\t_ = 1\n"
            "}\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert not any(
        d.path.endswith(".go") and d.confidence == Confidence.EXTRACTED
        for d in graph.dead_code
    ), graph.dead_code


def test_go_liveness_disabled_without_tree_sitter(monkeypatch):
    """Without tree-sitter, Go call edges cannot be extracted — Go files must
    drop out of file liveness instead of flooding unwired (fail closed)."""
    from devcouncil.indexing import ts_imports
    from devcouncil.indexing.wiring import is_liveness_code_file

    monkeypatch.setattr(ts_imports, "tree_sitter_available", lambda: False)
    assert is_liveness_code_file("pkg/main.py") is True
    assert is_liveness_code_file("internal/thing.go") is False


# ---------------------------------------------------------------------------
# 7. True positives must survive the hardening
# ---------------------------------------------------------------------------


def test_orphan_module_and_dead_function_still_flagged(tmp_path):
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": (
            "from pkg.used import helper\n"
            "def main():\n"
            "    return helper()\n"
        ),
        "pkg/used.py": (
            "def helper():\n"
            "    return 1\n"
            "def stranded_helper():\n"
            "    return 2\n"
        ),
        "pkg/orphan.py": "value = 1\n",
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "pkg/orphan.py" in graph.unwired_candidates, graph.unwired_candidates
    dead = [d for d in graph.dead_code if d.id.endswith("::stranded_helper")]
    assert dead, graph.dead_code
    assert dead[0].confidence == Confidence.EXTRACTED
    assert not any(d.id.endswith("::helper") for d in graph.dead_code)


def test_shard_carries_content_exemption_and_backfills(tmp_path):
    """Incremental shard path must agree with the full build — including for
    pre-upgrade shards persisted without the new key (disk backfill)."""
    from devcouncil.indexing.graph.build import extract_all
    from devcouncil.indexing.graph.liveness import (
        build_liveness_shard,
        file_liveness_from_shards,
    )

    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "go.mod": "module example.com/app\n\ngo 1.21\n",
        "internal/assets/embed.go": (
            "package assets\n\n"
            'import "embed"\n\n'
            "//go:embed all:dist\n"
            "var Dist embed.FS\n"
        ),
        "stray/orphan.py": "value = 1\n",
    })
    _commit(tmp_path)
    files = [
        "pkg/__init__.py",
        "pkg/main.py",
        "internal/assets/embed.go",
        "stray/orphan.py",
    ]
    extractions = extract_all(tmp_path, files)
    shards = {
        path: build_liveness_shard(tmp_path, ext) for path, ext in extractions.items()
    }
    assert shards["internal/assets/embed.go"]["content_exemption"] == "side_effect"
    assert shards["stray/orphan.py"]["content_exemption"] is None

    _roots, unwired, _unreach, _unrel = file_liveness_from_shards(
        files, [], shards,
        root=tmp_path,
        entry_roots=["pkg/main.py"],
        production_entry_roots=["pkg/main.py"],
    )
    assert "internal/assets/embed.go" not in unwired, unwired
    assert "stray/orphan.py" in unwired, unwired

    # Pre-upgrade shards without the key: backfill from disk, same verdicts.
    legacy_shards = {
        path: {k: v for k, v in shard.items() if k != "content_exemption"}
        for path, shard in shards.items()
    }
    _roots, unwired_legacy, _unreach, _unrel = file_liveness_from_shards(
        files, [], legacy_shards,
        root=tmp_path,
        entry_roots=["pkg/main.py"],
        production_entry_roots=["pkg/main.py"],
    )
    assert unwired_legacy == unwired


def test_stress_synthetic_repo_precision(tmp_path):
    """~165-file repo mixing every known-live shape across Python/Go/JS.

    Precision contract: zero known-live files at unwired, zero extracted-tier
    dead symbols outside the planted dead set — while every plant is caught.
    """
    files: dict[str, str] = {
        "pyproject.toml": (
            '[project]\nname="t"\nversion="0"\n[project.scripts]\ncli="app.cli:main"\n'
        ),
        "app/__init__.py": "",
        "go.mod": "module example.com/app\n\ngo 1.21\n",
    }

    n_mods, n_dead = 60, 15
    imports, calls = [], []
    planted_dead = set()
    for i in range(n_mods):
        body = f"def use_{i}():\n    return {i}\n"
        if i < n_dead:
            body += f"def dead_fn_{i}():\n    return {i}\n"
            planted_dead.add(f"app/mod_{i}.py::dead_fn_{i}")
        files[f"app/mod_{i}.py"] = body
        imports.append(f"from app.mod_{i} import use_{i}")
        calls.append(f"    use_{i}()")
    files["app/cli.py"] = (
        "\n".join(imports) + "\ndef main():\n" + "\n".join(calls) + "\n    return 0\n"
    )

    # Generated stubs (Python + Go).
    for i in range(12):
        files[f"gen/g{i}_pb2.py"] = _PB2_HEADER + "DESCRIPTOR = None\n"
    for i in range(8):
        files[f"gen/g{i}_pb2_grpc.py"] = (
            _PB2_GRPC_HEADER
            + f"class Stub{i}:\n    def Call{i}(self, request):\n        return request\n"
        )
    for i in range(10):
        files[f"goproto/p{i}.pb.go"] = (
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n"
            f"package goproto\n\ntype P{i} struct{{}}\n"
        )

    # Go side-effect carriers.
    for i in range(5):
        files[f"goapp/embed_{i}.go"] = (
            f"package goapp\n\nimport \"embed\"\n\n//go:embed all:dist{i}\nvar D{i} embed.FS\n"
        )
        files[f"goapp/load_{i}.go"] = (
            f"package goapp\n\nimport \"os\"\n\nfunc init() {{\n"
            f'\tos.Setenv("K{i}", "1")\n}}\n'
        )

    # Externally-launched entry scripts (__main__ guard).
    for i in range(10):
        files[f"tools_rt/app_{i}.py"] = (
            f"def serve_{i}():\n    return {i}\n\n"
            f'if __name__ == "__main__":\n    serve_{i}()\n'
        )

    # Launcher-file references: Dockerfile + Procfile.
    files["svc/Dockerfile"] = "FROM python:3.12-slim\n" + "".join(
        f"RUN python job_{i}.py\n" for i in range(5)
    )
    for i in range(5):
        files[f"svc/job_{i}.py"] = f"def job_{i}():\n    return {i}\njob_{i}()\n"
    files["svc2/__init__.py"] = ""
    files["Procfile"] = "".join(
        f"q{i}: python -m svc2.q_{i}\n" for i in range(5)
    )
    for i in range(5):
        files[f"svc2/q_{i}.py"] = f"def loop_{i}():\n    return {i}\nloop_{i}()\n"

    # Barrel packages.
    for i in range(5):
        files[f"lib_{i}/__init__.py"] = (
            f"from .impl import f_{i}\n__all__ = ['f_{i}']\n"
        )
        files[f"lib_{i}/impl.py"] = f"def f_{i}():\n    return {i}\n"

    # JS wired from src/index.js (conventional main seed).
    js_imports = []
    for i in range(20):
        files[f"src/w_{i}.js"] = f"export function work_{i}() {{ return {i} }}\n"
        js_imports.append(f"import {{ work_{i} }} from './w_{i}.js';")
    files["src/index.js"] = "\n".join(js_imports) + "\n"

    # Planted orphans — the only files that SHOULD be unwired.
    planted_orphans = set()
    for i in range(6):
        files[f"stray/orphan_{i}.py"] = f"value_{i} = {i}\n"
        planted_orphans.add(f"stray/orphan_{i}.py")

    _write(tmp_path, files)
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)

    assert set(graph.unwired_candidates) == planted_orphans, (
        sorted(set(graph.unwired_candidates) ^ planted_orphans)
    )

    extracted = {
        d.id for d in graph.dead_code if d.confidence == Confidence.EXTRACTED
    }
    assert extracted == planted_dead, sorted(extracted ^ planted_dead)

    # Generated code must not surface at any tier.
    assert not any(
        d.path.startswith(("gen/", "goproto/")) for d in graph.dead_code
    ), [d.id for d in graph.dead_code if d.path.startswith(("gen/", "goproto/"))]


def test_plain_go_helper_file_still_unwired(tmp_path):
    """Handwritten Go file with no embed/init/main and no callers stays flagged."""
    _write(tmp_path, {
        "pyproject.toml": _PYPROJECT,
        "pkg/__init__.py": "",
        "pkg/main.py": "def main():\n    return 0\n",
        "go.mod": "module example.com/app\n\ngo 1.21\n",
        "cmd/main.go": (
            "package main\n\n"
            "func main() {\n"
            "\t_ = 1\n"
            "}\n"
        ),
        "internal/spare/helpers.go": (
            "package spare\n\n"
            "func Helper() int { return 1 }\n"
        ),
    })
    _commit(tmp_path)
    graph = build_code_graph(tmp_path)
    assert "internal/spare/helpers.go" in graph.unwired_candidates, (
        graph.unwired_candidates
    )
