use devmap_extract::*;

#[test]
fn test_python_extraction() {
    let code = r#"
def hello(name: str):
    """Greeting function."""
    print("Hello", name)

class Service:
    def run(self):
        hello("world")
"#;
    let ext = extract_file("src/service.py", code);
    assert_eq!(ext.language, "python");
    assert!(!ext.symbols.is_empty());
    assert!(ext.symbols.iter().any(|s| s.name == "hello"));
    assert!(ext.symbols.iter().any(|s| s.name == "Service"));
    assert!(ext
        .calls
        .iter()
        .any(|c| c.callee_name == "hello" || c.callee_name == "print"));
}

#[test]
fn test_rust_extraction() {
    let code = r#"
fn process_data(input: &str) {
    println!("{}", input);
}

pub struct Config {
    pub port: u16,
}
"#;
    let ext = extract_file("src/config.rs", code);
    assert_eq!(ext.language, "rust");
    assert!(ext.symbols.iter().any(|s| s.name == "process_data"));
    assert!(ext.symbols.iter().any(|s| s.name == "Config"));
}

#[test]
fn test_wiring_exemptions() {
    let code = "// @generated by protoc\npackage pb;";
    let ext = extract_file("src/api_pb.go", code);
    assert!(ext
        .wiring
        .iter()
        .any(|w| w.kind == WiringKind::GeneratedFile));
}

#[test]
fn test_adversarial_inputs() {
    // Malformed syntax
    let bad_code = "def ((((( unclosed parentheses fn(): {{{{";
    let ext = extract_file("src/bad.py", bad_code);
    assert!(matches!(ext.parse_outcome, ParseOutcome::Partial { .. }));

    // Extremely long line (100,000 chars)
    let long_line = format!("def fn_long(): {}", "x = 1; ".repeat(10000));
    let ext_long = extract_file("src/long.py", &long_line);
    assert!(matches!(
        ext_long.parse_outcome,
        ParseOutcome::Clean | ParseOutcome::Partial { .. }
    ));
    assert!(ext_long
        .symbols
        .iter()
        .any(|symbol| symbol.name == "fn_long"));

    // Null bytes / binary string.
    //
    // This asserted `Partial` — "we parsed it and found errors" — which is what
    // tree-sitter-rust happens to do. It is now `Failed`, because a NUL-bearing
    // source is refused at the boundary before any grammar sees it. That is not
    // a style preference: the vendored COBOL grammar **does not terminate** on
    // this input (measured 2026-09-04: six bytes, over three minutes, no end),
    // and tree-sitter's progress callback is never reached from inside a
    // scanner that is spinning, so there is no in-process bound that would stop
    // it. The guard has to be uniform — a per-language exemption would
    // reintroduce the hang for exactly the language that hangs.
    //
    // The test's intent is unchanged and better served: adversarial input is
    // still handled without crashing, and is now reported honestly rather than
    // yielding symbols extracted from binary.
    let bin_code = "fn main() { \0\0\0 }";
    let ext_bin = extract_file("src/bin.rs", bin_code);
    match &ext_bin.parse_outcome {
        ParseOutcome::Failed { reason } => {
            assert!(
                reason.contains("NUL"),
                "the refusal must name why: {reason:?}"
            )
        }
        other => panic!("a NUL-bearing source must be refused, got {other:?}"),
    }
}

#[test]
fn zero_argument_require_does_not_fabricate_a_module_name() {
    let ext = extract_file("src/empty-require.js", "require();\n");
    assert!(
        ext.imports.is_empty(),
        "zero-argument require is not an import"
    );
}

#[test]
fn deeply_nested_syntax_does_not_recurse_the_rust_call_stack() {
    let depth = 10_000;
    let source = format!("value = {}0{}\n", "(".repeat(depth), ")".repeat(depth));
    let ext = extract_file("src/deep.py", &source);
    assert!(matches!(
        ext.parse_outcome,
        ParseOutcome::Clean | ParseOutcome::Partial { .. }
    ));
    assert_eq!(ext.content_hash, content_hash(&source));
}
